---

version: "v-{build}"

image: Visual Studio 2017

clone_folder: C:\projects\lwjgl-example

environment:
  GRAALVM_HOME: C:\projects\lwjgl-example\graalvm\graalvm-ce-java11-20.1.0
  BOOTLEG_VERSION: 0.1.9

cache:
  - C:\ProgramData\chocolatey\lib -> project.clj, appveyor.yml
  - '%USERPROFILE%\.m2 -> project.clj'
  - 'openjdk -> appveyor.yml'

branches:
  only:
    - master

build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein self-install

    powershell -Command "if (Test-Path('openjdk')) { return } else { (New-Object Net.WebClient).DownloadFile('https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_windows-x64_bin.zip', 'openjdk-14.0.1_windows-x64_bin.zip') }"

    powershell -Command "if (Test-Path('openjdk')) { return } else { Expand-Archive openjdk-14.0.1_windows-x64_bin.zip openjdk }"

    call choco install wixtoolset

    dir

    dir openjdk

    set JAVA_HOME=C:\projects\lwjgl-example\openjdk\jdk-14.0.1

    set PATH=%JAVA_HOME%\bin;%PATH%

    java -version

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://build.lwjgl.org/stable/windows/x64/lwjgl.dll', 'lwjgl.dll')"

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://build.lwjgl.org/stable/windows/x64/lwjgl_opengl.dll', 'lwjgl_opengl.dll')"

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://build.lwjgl.org/stable/windows/x64/glfw.dll', 'glfw.dll')"

    lein uberjar

    mkdir jpack

    copy target\uberjar\lwjgl-example-0.1.0-SNAPSHOT-standalone.jar jpack

    copy lwjgl.dll jpack

    copy lwjgl_opengl.dll jpack

    copy glfw.dll jpack

    jpackage --name lwjglexample --input jpack --main-jar lwjgl-example-0.1.0-SNAPSHOT-standalone.jar --license-file LICENSE --type msi --win-console

    jpackage --name lwjglexample --input jpack --main-jar lwjgl-example-0.1.0-SNAPSHOT-standalone.jar --license-file LICENSE --type exe --win-console

    dir

    dir jpack

    jpackage --help

test: off

artifacts:
- path: lwjglexample-*.msi
  name: lwjglexample-msi
- path: lwjglexample-*.exe
  name: lwjglexample-exe
